// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependency

import (
	"github.com/chatApp/internal/database"
	"github.com/chatApp/internal/http/api"
	"github.com/chatApp/internal/http/controller"
	"github.com/chatApp/internal/pkg/config"
	"github.com/chatApp/internal/pkg/security"
	"github.com/chatApp/internal/pkg/util"
	"github.com/chatApp/internal/repository"
	"github.com/chatApp/internal/service"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Injectors from wire.go:

func NewConfig(opt config.Options) (config.ChatApiConfig, error) {
	chatApiConfig, err := config.NewConfig(opt)
	if err != nil {
		return config.ChatApiConfig{}, err
	}
	return chatApiConfig, nil
}

func NewDatabaseConfig(cfg config.ChatApiConfig) (*pgxpool.Pool, error) {
	pool := database.NewDB(cfg)
	return pool, nil
}

func NewChatAppApi(cfg config.ChatApiConfig, db *pgxpool.Pool) (*api.ChatApi, error) {
	personnelRepository := repository.NewPersonnelRepository(db)
	personnelService := service.NewPersonnelService(personnelRepository)
	personnelController := controller.NewPersonnelController(personnelService)
	appUtil := util.NewAppUtil()
	manager := security.NewJwtSecurityManager(cfg)
	transactioner := repository.NewTransactioner(db)
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(appUtil, cfg, personnelRepository, manager, transactioner, userRepository)
	userController := controller.NewUserController(userService)
	chatApi := api.NewChatApi(cfg, personnelController, userController)
	return chatApi, nil
}
